package e_commerce.com.example.e.commerce.security;

import e_commerce.com.example.e.commerce.models.Role;
import e_commerce.com.example.e.commerce.models.User;
import e_commerce.com.example.e.commerce.repos.UserRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;

@Component
public class AdminInitializer implements CommandLineRunner {

    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;
    private final DataSource dataSource;

    public AdminInitializer(UserRepository userRepository, PasswordEncoder passwordEncoder, DataSource dataSource) {
        this.userRepository = userRepository;
        this.passwordEncoder = passwordEncoder;
        this.dataSource = dataSource;
    }

    @Override
    public void run(String... args) throws Exception {
        // Fix PostgreSQL sequence / identity generator on product table if it is missing
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.execute("ALTER TABLE product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY");
            System.out.println("Database Migration: Successfully added IDENTITY generator to product table id column.");
        } catch (Exception e) {
            System.out.println("Database Migration Info: Product table identity check completed (" + e.getMessage() + ")");
        }

        // Synchronize sequence value with the maximum existing ID to avoid duplicate key errors
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.execute("SELECT setval(pg_get_serial_sequence('product', 'id'), coalesce(max(id), 1)) FROM product");
            System.out.println("Database Migration: Successfully synchronized product ID sequence.");
        } catch (Exception e) {
            System.out.println("Database Migration Info: Product sequence synchronization completed (" + e.getMessage() + ")");
        }

        if (userRepository.findByEmail("admin@gmail.com").isEmpty()) {
            User admin = new User();
            admin.setName("Admin");
            admin.setEmail("admin@gmail.com");
            admin.setPassword(passwordEncoder.encode("admin123"));
            admin.setRole(Role.ADMIN);
            userRepository.save(admin);
            System.out.println("Default admin account created: admin@gmail.com / admin123");
        }
    }
}
