spring.application.name=e.commerce

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}


spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

cloudinary.cloud-name=dlb4zqggk
cloudinary.api-key=957563956245218
cloudinary.api-secret=x00s4DkLahpjwosVIpY2bpsrHvY

# JWT Configuration
jwt.expiration=3600000
#jwt.secret=Q9vK2mL8xT4pR7sN1wZ6yF3aJ8uD5gH2eB9cX4rP7qL1nM6tV2kS8uY5iC3oW9zA

jwt.secret=${JWT_SECRET}

# JavaMailSender (Gmail SMTP) Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.enabled=${GMAIL_ENABLED:false}

